name: Build and Push to GHCR and Docker Hub

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # For checkout
      packages: write  # For GHCR push (critical for this error)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract tag name for versioned releases
        id: meta
        run: |
          if [[ "${{ github.ref }}" =~ ^refs/tags/v([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            echo "tag=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          else
            echo "tag=main" >> $GITHUB_OUTPUT
          fi

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to both registries
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/jnbarlow/monero-nodeboard:${{ steps.meta.outputs.tag }}
            ghcr.io/jnbarlow/monero-nodeboard:${{ github.sha }}
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/monero-nodeboard:${{ steps.meta.outputs.tag }}
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/monero-nodeboard:${{ github.sha }}
          platforms: linux/amd64  # Add linux/arm64 if needed
          cache-from: type=gha
          cache-to: type=gha,mode=max
